name: Continues Integration Pipeline

on:
  pull_request:
      branches: [ main ]
  workflow_dispatch:
    
jobs:
  dockerimagebuild:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        
        - name: FrontEndBuildAndPush
          uses: docker/build-push-action@v6
          with:
            file: ./Dockerfile.fe
            push: true
            tags: devagunay/gitcourserepo:frontend
        
        - name: BackEndBuildAndPush
          uses: docker/build-push-action@v6
          with:
            file: ./Dockerfile.fe
            push: true
            tags: devagunay/gitcourserepo:backend
        
        - name: DatabaseBuildAndPush
          uses: docker/build-push-action@v6
          with:
            file: ./Dockerfile.fe
            push: true
            tags: devagunay/gitcourserepo:database